---
output: github_document
---

# Prerequisites

Before submitting a bug report, please tick the appropriate boxes. <!-- Delete this line when filing the bug report. -->

[ ] I am running the latest version of the package.

[ ] I checked the documentation and found no answer.

[ ] I checked to make sure that this issue has not already been filed.

<!-- To tick the box, simply add x inside []. -->

$\underline{\text{Attention!}}$ If you have a question, please do not use this form. Go to the [discussion forum](https://github.com/GianlucaCarpigo/VECM/discussions) and ask others for help. <!-- Delete this line when filing the bug report. -->

# Expected behavior

Please describe the behavior you are expecting.

# Current behavior

Please describe the behavior you are experiencing.

# Failure information

Please provide information about the bug.

## Steps to reproduce

Please provide detailed steps to reproduce the bug.

$\underline{\text{Attention!}}$ The **reprex** package may be useful here. If you have never heard of **reprex** before, start by reading this [guide](https://www.tidyverse.org/help/#reprex). <!-- Delete this line when filing the bug report. -->

## Context

Please provide any relevant information about your setup.

$\underline{\text{Attention!}}$ The content of `sessioninfo::session_info()` is a good starting point. <!-- Delete this line when filing the bug report. -->

## Failure logs

Please include any relevant log snippets or files here.
